### ISSUE TITLE
Debugging doesn't start

### ISSUE THREAD

**Issue by nbros** [OlegKunitsyn/gnucobol-debug#130]
After configuring launch.json and hitting F5 in a compiled Cobol file, debugging doesn't start and I see the following error in the Extension host (remote) output:
```
[error] TypeError: Cannot read properties of undefined (reading 'pid')
	at Timeout._onTimeout (/home/user/.vscode-server/extensions/olegkunitsyn.gnucobol-debug-2.31.37/out/src/mi2.js:477:32)
	at listOnTimeout (node:internal/timers:559:17)
	at processTimers (node: internal/timers:502:7)
```

**Comment by GitMensch** [comment]
How does your configuration look like?

**Comment by nbros** [comment]
I have installed and configured:
- VS Code, IBM Z Open Editor and COBOL debugger.
- cobc (GnuCOBOL) 3.1.2.0
- GNU gdb (Ubuntu 12.1-0ubuntu1~22.04) 12.1

This is my launch.json:
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "COBOL debugger",
            "type": "gdb",
            "request": "launch",
            "cobcargs": [
                "-free",
                "-x"
            ],
            "coverage": true
        },
    ]
}
```

**Comment by martin3000** [comment]
When I press F5 and select "Cobol debugger", als nothing happens. But where to I find the Extension host (remote) output?

**Comment by GitMensch** [comment]
> Is it possible that npm (nodejs) must be installed?

No.

> When I press F5 and select "Cobol debugger", als nothing happens.

You _may_ have to create a launch.json, if this wasn't done automatically (which would be a bug that should be tracked in a separate issue).

If you have this configuration then you may need to set a breakpoint in your COBOL source to not start, run, finish all in a row.

**Comment by martin3000** [comment]
I created a launch.json in ~/.vscode , but it did not help.

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "COBOL debugger",
            "type": "gdb",
            "request": "launch",
            "cobcargs": ["-x"]
        }
    ]
}
```

**Comment by martin3000** [comment]
Ok after adding a folder to the workspace it was possible to create a new launch.json. 
Now I get this error:
```
2023-07-24 11:32:13.030 [error] TypeError: Cannot read properties of undefined (reading 'pid')
	at Timeout._onTimeout (/home/jms/.vscode/extensions/olegkunitsyn.gnucobol-debug-2.32.1/out/src/mi2.js:524:32)
	at listOnTimeout (node:internal/timers:559:17)
	at process.processTimers (node:internal/timers:502:7)
```
It looks like it lost the connection to the spawned cobc or it could not start cobc.
