### ISSUE TITLE
TypeError: Cannot read property 'on' of undefined

### ISSUE THREAD

**Issue by GitMensch** [OlegKunitsyn/gnucobol-debug#67]
~~~
TypeError: Cannot read property 'on' of undefined
	at MI2.stop (/home/so/.vscode-oss/extensions/olegkunitsyn.gnucobol-debug-1.31.24/out/src/mi2.js:391:22)
	at GDBDebugSession.disconnectRequest (/home/so/.vscode-oss/extensions/olegkunitsyn.gnucobol-debug-1.31.24/out/src/gdb.js:175:29)
	at GDBDebugSession.dispatchRequest (/home/so/.vscode-oss/extensions/olegkunitsyn.gnucobol-debug-1.31.24/node_modules/vscode-debugadapter/lib/debugSession.js:385:22)
	at GDBDebugSession.handleMessage (/home/so/.vscode-oss/extensions/olegkunitsyn.gnucobol-debug-1.31.24/node_modules/vscode-debugadapter/lib/protocol.js:60:18)
	at T.sendMessage (/usr/share/codium/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:862:988)
	at v.$sendDAMessage (/usr/share/codium/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:853:138)
	at m._doInvokeHandler (/usr/share/codium/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:801:683)
	at m._invokeHandler (/usr/share/codium/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:801:375)
	at m._receiveRequest (/usr/share/codium/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:800:14)
	at m._receiveOneMessage (/usr/share/codium/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:798:832)
	at /usr/share/codium/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:797:34
	at l.fire (/usr/share/codium/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:45:801)
	at v.fire (/usr/share/codium/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:235:849)
	at /usr/share/codium/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:975:744
	at l.fire (/usr/share/codium/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:45:801)
	at v.fire (/usr/share/codium/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:235:849)
	at t.PersistentProtocol._receiveMessage (/usr/share/codium/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:240:276)
	at /usr/share/codium/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:237:357
	at l.fire (/usr/share/codium/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:45:801)
	at p.acceptChunk (/usr/share/codium/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:233:393)
	at /usr/share/codium/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:232:753
	at Socket.t (/usr/share/codium/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:241:826)
	at Socket.emit (events.js:203:13)
	at addChunk (_stream_readable.js:295:12)
	at readableAddChunk (_stream_readable.js:276:11)
	at Socket.Readable.push (_stream_readable.js:210:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
~~~

Happened when GDB launch had issues, "looked" like it hanged and I've pressed "stop".

I'd "obviously" prefer to see an error message for the launch.
The actual issue was the the cwd definition pointed in launch.json pointed to a not existing directory.

**Comment by brunopacheco1** [comment]
@GitMensch Hi Simon, the changes were merged into master, as soon as @OlegKunitsyn releases a new tag, could you check the solution?

Basically, if the CWD path is not valid, a dialog with an error is presented and the launch.json file should be opened.
