### ISSUE TITLE
add CI/CD

### ISSUE THREAD

**Issue by GitMensch** [OlegKunitsyn/gnucobol-debug#71]
It would be very nice to have CI/CD active for this repository.
While I have no clue about what actually is possible or not with .ts and .vsix, I "imagine" the following:

* build the extension
* verify (run everything under "tests", this may/may not need some additional work)
* create a .vsix

This would be done on any commit/pr so the results are easily testable (if they build at all, which I question most for any direct source changes  I do).

As a next step it could do the publishing to registry+market for every new tag created (or at least the ones that look like a version number), making that part easier and faster too.

**Comment by OlegKunitsyn** [comment]
Actions were there. I have disabled automatic testing due to an unreproducible false positive. I could enable the actions.
Regards automatic deployment. At the moment we can't test ui and related aspects of the extension. Therefore, I prefer the accepence testing before each release.

**Comment by GitMensch** [comment]
Thank you for the information. Yes, please try to re-enable all actions including the testing, we may find the false positive and maybe it is already gone.
For the automated release + deployment: if it is only done for a tag then you can manually test master (or even create a release branch to ensure no intermediate commits) and when the testing (of the CI created .vsix) shows good results do the tagging and the release + uploads will "magically" (automated) happen. At least that was my suggestion :-)

**Comment by GitMensch** [comment]
@OlegKunitsyn It seems that the current workflow is broken, can you please delete and re-create it, giving a name and checking the repo permissions allow the CI?

**Comment by OlegKunitsyn** [comment]
> 48 passing (99ms) 1 failing

**Comment by GitMensch** [comment]
Yes, the [test](https://github.com/OlegKunitsyn/gnucobol-debug/runs/884504427?check_suite_focus=true#step:6:182) shows:

~~~
  C code parse
       Minimal:

      AssertionError [ERR_ASSERTION]: 105 == 0
      + expected - actual

      -105
      +0
      
      at Context.<anonymous> (out/test/parser.c.test.js:18:16)
      at processImmediate (internal/timers.js:456:21)
~~~

That is the exact same test result that happens on my other machine where I've only got NPM binaries setup to be able to possibly test anything about the extension development.

**Comment by brunopacheco1** [comment]
I thought I had fixed an issue related to this test.

Back the time when I fixed, basically the parser.c.ts checks a directory path that is written inside the C file, but the C file and this path info are generated by GC during compilation time.

As the test is using C file is fixed as this path checking depends on the environment it is running, the test will fail as the current path value is pointing to an unexisting absolute file path. The solution was checking the relative path instead.

In this case, it was  the file `hello.c.h`, line 2.

@OlegKunitsyn could you double-check if this is still the same issue? It looks it is comparing absolute file paths again.

**Comment by OlegKunitsyn** [comment]
Yes, it is. https://github.com/OlegKunitsyn/gnucobol-debug/runs/682143695?check_suite_focus=true
